//! Spec-Kit Check Tool
//!
//! Validates that required tools are installed.

use anyhow::{Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::mcp::types::{ContentBlock, ToolDefinition, ToolResult};
use crate::tools::Tool;

/// Parameters for the speckit_check tool
#[derive(Debug, Deserialize, Serialize)]
pub struct CheckParams {
    /// Check for spec-kit CLI
    #[serde(default = "default_true")]
    check_speckit: bool,

    /// Check for git
    #[serde(default = "default_true")]
    check_git: bool,

    /// Check for common AI coding assistants
    #[serde(default = "default_true")]
    check_ai_tools: bool,
}

fn default_true() -> bool {
    true
}

impl Default for CheckParams {
    fn default() -> Self {
        Self {
            check_speckit: true,
            check_git: true,
            check_ai_tools: true,
        }
    }
}

/// Tool for checking required tool installations
#[derive(Default)]
pub struct CheckTool {}

impl CheckTool {
    /// Create a new check tool
    pub fn new() -> Self {
        Self::default()
    }

    /// Check if a command is available
    async fn check_command(&self, command: &str) -> bool {
        async_process::Command::new(command)
            .arg("--version")
            .stdout(async_process::Stdio::null())
            .stderr(async_process::Stdio::null())
            .status()
            .await
            .map(|s| s.success())
            .unwrap_or(false)
    }
}

#[async_trait]
impl Tool for CheckTool {
    fn definition(&self) -> ToolDefinition {
        ToolDefinition {
            name: "speckit_check".to_string(),
            description: "Validate that required tools are installed for spec-kit development"
                .to_string(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "check_speckit": {
                        "type": "boolean",
                        "default": true,
                        "description": "Check if spec-kit CLI is installed"
                    },
                    "check_git": {
                        "type": "boolean",
                        "default": true,
                        "description": "Check if git is installed"
                    },
                    "check_ai_tools": {
                        "type": "boolean",
                        "default": true,
                        "description": "Check for AI coding assistants (claude, cursor, etc.)"
                    }
                },
                "required": []
            }),
        }
    }

    async fn execute(&self, params: Value) -> Result<ToolResult> {
        let params: CheckParams =
            if params.is_null() || params.as_object().is_some_and(|o| o.is_empty()) {
                CheckParams::default()
            } else {
                serde_json::from_value(params).context("Failed to parse check parameters")?
            };

        tracing::info!("Checking tool installations");

        let mut output = String::from("# Development Environment Validation Report\n\n");
        output.push_str("**Generated by**: spec-kit MCP Server\n");
        output
            .push_str("**Purpose**: Validate required tools for spec-kit development workflow\n\n");
        output.push_str("---\n\n");

        let mut all_required_available = true;
        let mut missing_required = Vec::new();
        let mut available_optional = Vec::new();
        let mut missing_optional = Vec::new();

        // Check git (required)
        if params.check_git {
            let git_available = self.check_command("git").await;
            if git_available {
                output.push_str("✓ **git** - Version control system (REQUIRED)\n");
                output.push_str("  Status: Installed and available\n\n");
            } else {
                output.push_str("✗ **git** - Version control system (REQUIRED)\n");
                output.push_str("  Status: NOT INSTALLED\n");
                output.push_str("  Action: Install from https://git-scm.com/downloads\n");
                output.push_str("  Impact: Cannot initialize repositories or track changes\n\n");
                all_required_available = false;
                missing_required.push("git");
            }
        }

        // Check spec-kit (this MCP server provides spec-kit functionality)
        if params.check_speckit {
            output.push_str("✓ **spec-kit MCP Server** - Core functionality provider (REQUIRED)\n");
            output.push_str("  Status: Running and operational\n");
            output.push_str("  Provides: All spec-kit commands and workflow tools\n\n");
        }

        // Check AI tools (optional but recommended)
        if params.check_ai_tools {
            output.push_str("## AI Coding Assistants (OPTIONAL)\n\n");
            output.push_str(
                "These tools enhance the development experience but are not required.\n\n",
            );

            let ai_tools = vec![
                ("claude", "Claude Desktop", "https://claude.ai/download"),
                ("cursor", "Cursor IDE", "https://cursor.sh"),
                ("code", "VS Code", "https://code.visualstudio.com"),
            ];

            for (cmd, name, url) in ai_tools {
                let available = self.check_command(cmd).await;
                if available {
                    output.push_str(&format!("✓ **{}** - Installed\n", name));
                    output.push_str("  Status: Available for AI-assisted development\n\n");
                    available_optional.push(name);
                } else {
                    output.push_str(&format!("○ **{}** - Not found\n", name));
                    output.push_str(&format!("  Install from: {}\n", url));
                    output.push_str("  Benefit: AI-powered code generation and assistance\n\n");
                    missing_optional.push(name);
                }
            }
        }

        // Summary section with actionable guidance
        output.push_str("---\n\n");
        output.push_str("## Environment Status Summary\n\n");

        if all_required_available {
            output.push_str("✅ **READY**: All required tools are installed\n\n");
            output.push_str("### Your Development Environment\n\n");
            output.push_str("- **Core Tools**: All required tools available\n");
            output.push_str(&format!(
                "- **AI Assistants**: {} available, {} optional tools not installed\n",
                available_optional.len(),
                missing_optional.len()
            ));
            output.push_str("- **Status**: Ready for spec-kit development workflow\n\n");

            output.push_str("### Next Steps\n\n");
            output.push_str("1. Initialize a new project: Use `speckit_init` tool\n");
            output.push_str("2. Define project principles: Use `speckit_constitution` tool\n");
            output.push_str("3. Specify requirements: Use `speckit_specify` tool\n");
            output.push_str("4. Create technical plan: Use `speckit_plan` tool\n");
            output.push_str("5. Generate task list: Use `speckit_tasks` tool\n");
            output.push_str("6. Execute implementation: Use `speckit_implement` tool\n\n");

            if !missing_optional.is_empty() {
                output.push_str("### Optional Enhancements\n\n");
                output.push_str(
                    "Consider installing AI coding assistants for enhanced productivity:\n",
                );
                for tool in &missing_optional {
                    output.push_str(&format!("- {}\n", tool));
                }
                output.push_str("\nThese tools provide AI-powered code generation, refactoring, and assistance.\n\n");
            }
        } else {
            output.push_str("⚠️ **ACTION REQUIRED**: Missing required tools\n\n");
            output.push_str("### Missing Required Tools\n\n");
            for tool in &missing_required {
                output.push_str(&format!(
                    "- **{}**: Must be installed before proceeding\n",
                    tool
                ));
            }
            output.push_str("\n### Installation Instructions\n\n");
            if missing_required.contains(&"git") {
                output.push_str("**Install git**:\n");
                output.push_str("- Windows: Download from https://git-scm.com/downloads\n");
                output.push_str("- macOS: `brew install git` or download from website\n");
                output.push_str("- Linux: `sudo apt install git` (Debian/Ubuntu) or `sudo yum install git` (RHEL/CentOS)\n\n");
            }
            output.push_str("After installation, run this check again to verify.\n\n");
        }

        output.push_str("### Confidence Assessment\n\n");
        output.push_str(&format!(
            "- **Environment Readiness**: {}%\n",
            if all_required_available { 100 } else { 50 }
        ));
        output.push_str(&format!(
            "- **Required Tools**: {}/{} available\n",
            if all_required_available { 1 } else { 0 },
            1
        ));
        output.push_str(&format!(
            "- **Optional Tools**: {}/{} available\n",
            available_optional.len(),
            available_optional.len() + missing_optional.len()
        ));

        Ok(ToolResult {
            content: vec![ContentBlock::text(output)],
            is_error: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_check_tool_definition() {
        let tool = CheckTool::new();
        let def = tool.definition();

        assert_eq!(def.name, "speckit_check");
        assert!(!def.description.is_empty());
    }

    #[tokio::test]
    async fn test_check_tool_execute() {
        let tool = CheckTool::new();

        // Test with default params
        let result = tool.execute(json!({})).await.unwrap();
        assert!(!result.content.is_empty());

        // Test with specific params
        let params = json!({
            "check_speckit": true,
            "check_git": true,
            "check_ai_tools": false
        });

        let result = tool.execute(params).await.unwrap();
        assert!(!result.content.is_empty());
    }
}
